# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: genui_a2ui
description: Integration package for genui and A2UI Streaming UI Protocol.
version: 0.5.0
homepage: https://github.com/flutter/genui/packages/genui_a2ui
license: BSD-3-Clause
issue_tracker: https://github.com/flutter/genui/issues

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7 <4.0.0"

resolution: workspace

dependencies:
  a2a: ^3.1.0
  flutter:
    sdk: flutter
  genui: ^0.5.0
  json_schema_builder: ^0.1.3
  logging: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
