name: genui_client
description: "An app that generates user interfaces on the fly using AI."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  file: ^7.0.1
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  json_rpc_2: ^4.0.0
  platform: ^3.1.6
  stream_channel: ^2.1.4
  web_socket_channel: ^3.0.3

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
